/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
"use strict";var a=Object.defineProperty;var u=Object.getOwnPropertyDescriptor;var c=Object.getOwnPropertyNames;var g=Object.prototype.hasOwnProperty;var i=(l,o)=>{for(var e in o)a(l,e,{get:o[e],enumerable:!0})},r=(l,o,e,s)=>{if(o&&typeof o=="object"||typeof o=="function")for(let n of c(o))!g.call(l,n)&&n!==e&&a(l,n,{get:()=>o[n],enumerable:!(s=u(o,n))||s.enumerable});return l};var f=l=>r(a({},"__esModule",{value:!0}),l);var m={};i(m,{default:()=>d});module.exports=f(m);var t=require("obsidian"),d=class extends t.Plugin{async onload(){console.log("Test Plugin V2 loaded")}onunload(){console.log("Test Plugin V2 unloaded")}};
